### ISSUE TITLE
Store documentation out of date

### ISSUE THREAD

**Issue by harryhobson** [kevinpapst/kimai2-console#10]
Thank you for the fantastic software! I noticed that on the [store page](https://www.kimai.org/store/console-phar.html) the following command is displayed:
```
kimai configuration:create
```
Which will cause an error with the current version of the tool.

However the latest version in this repository says:
```
kimai configuration
```

Would it be possible to update the documentation on the store page?

**Comment by harryhobson** [comment]
Apologies I did not see #5 before creating this ticket, I will close as a duplicate

**Comment by kevinpapst** [comment]
Thanks for mentioning this. 
I haven't worked on or used this tool in a while and completely forgot about it.
I updated the store page.
