### ISSUE TITLE
kimai stop --description "Not updated, only adds the number 1"

### ISSUE THREAD

**Issue by rg-ch** [kevinpapst/kimai2-console#20]
Kimai - Remote Console version 1.0 2023-06-24,  PHP 8.2.6 

![image](https://github.com/kevinpapst/kimai2-console/assets/53338378/d5bf33e2-b63f-4037-8eee-9e7c917f4e28)

`kimai stop -d TestRG`  only adds the number 1 to the description field in the time sheet. Do I miss something ? 

![image](https://github.com/kevinpapst/kimai2-console/assets/53338378/27d64182-a7e5-4efb-b7f3-9b6f2804bdd2)

**Comment by kevinpapst** [comment]
Should be fixed with https://github.com/kevinpapst/kimai2-console/releases/tag/1.0.1
