### ISSUE TITLE
different requirements - which is correct?

### ISSUE THREAD

**Issue by ftrojahn** [kevinpapst/kimai2-console#6]
In the store https://www.kimai.org/store/console-phar.html it is written: 
> .. PHAR technology, so you need PHP >= 7.3 installed ...

whereas in this readme  https://github.com/kevinpapst/kimai2-console#readme  
> Requirements
> PHP 7.2.5

which one is correct?

Using recent Linux Mint 19.3 there's only php7.2 - so I get:

```
:~$ kimai configuration:create
 [ERROR] Failed execution: There are no commands defined in the "configuration" namespace.           
  There are no commands defined in the "configuration" namespace.
```

**Comment by kevinpapst** [comment]
I think 7.2 is correct.
There is an issue #5 that I need to update the store page... its outdated.
Please read the repo docs https://github.com/kevinpapst/kimai2-console - you'll see the command name changed.

So `kimai configuration` is what you are looking for

**Comment by kevinpapst** [comment]
Isn't mint actually based on Ubuntu? 
If you need a newer PHP version, you could try the ondrej ppa. Its very popular...

**Comment by ftrojahn** [comment]
Great, thanx for your quick reply. I've read the other issue about the store page, but did not recognise the different command. It's working now with 7.2.
